### ISSUE TITLE
Difference between ResponseEntity < Mono < ? > > and Mono < ResponseEntity < ? > >

### ISSUE THREAD

**Issue by patpatpat123** [armdev/reactive-dev#1]
Hello,

Thank you a lot for this project.

In your controller, you exposed something like:
public ResponseEntity < Mono < ? > > x() {
      and 
public Mono < ResponseEntity < ? > > y() {

Could you please let us know what are the difference between the two?
When is it better to use ResponseEntity < Mono < ? > > and when to use Mono < ResponseEntity < ? > >
Much appreciated.

**Comment by armdev** [comment]
Actually for fully use reactive stack you should not use response entity.
Mono and Flux does not support annotated endpoints (for example reactive filters does not work.)
I am personally think what functional programming in the REST controllers is not so good. Whats why I am using ResponseEntity . What is better? For me the best is ResponseEntity < ? > .

For more explanation we can refer @joshlong https://github.com/joshlong

**Comment by patpatpat123** [comment]
Hello,

Thank you for your reply.
Make sense. Can you also explain what is the core difference between the two?

**Comment by armdev** [comment]
1. ResponseEntity < Mono < ? > >  this is your response with Mono object,
this is correct.
2. Mono < ResponseEntity < ? > > this is contain one Response Entity which
is also can contain one Mono object, this is not Ok. Mono is a one type of
object .
In the REST you should return RESPONSE with some status (OK) and Body, so 1.
is better. !!!!!!!!!!!!!!


Armen Arzumanyan

Senior Software Architect

**Comment by patpatpat123** [comment]
Thank you!

**Comment by armdev** [comment]
Done
